// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearJobs() {
  return window['go']['ui']['App']['ClearJobs']();
}

export function DeleteJob(arg1) {
  return window['go']['ui']['App']['DeleteJob'](arg1);
}

export function GetFullInfo() {
  return window['go']['ui']['App']['GetFullInfo']();
}

export function GetInfo() {
  return window['go']['ui']['App']['GetInfo']();
}

export function GetJobPDF(arg1) {
  return window['go']['ui']['App']['GetJobPDF'](arg1);
}

export function GetJobs() {
  return window['go']['ui']['App']['GetJobs']();
}

export function GetStatus() {
  return window['go']['ui']['App']['GetStatus']();
}

export function SyncQueue() {
  return window['go']['ui']['App']['SyncQueue']();
}
