// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ClearJobs():Promise<void>;

export function DeleteJob(arg1:string):Promise<void>;

export function GetFullInfo():Promise<Record<string, any>>;

export function GetInfo():Promise<Record<string, string>>;

export function GetJobPDF(arg1:string):Promise<string>;

export function GetJobs():Promise<Array<models.PrintJob>>;

export function GetStatus():Promise<string>;

export function SyncQueue():Promise<void>;
